version: '3.7'

services:

  react:
    container_name: react
    build: .
    ports:
      - 3000:3000
    stdin_open: true
    mem_limit: 4G
    cpus: 1
    volumes:
      - .:/app
      - '/app/node_modules'
    command: npm start